const questions = [

  // ╔══════════════════════════════════════════════════════╗
  // ║              TUDOMÁNY – KÖNNYŰ (25)                  ║
  // ╚══════════════════════════════════════════════════════╝
  { text: "A fény sebessége vákuumban körülbelül 300 000 km/s.", answer: true, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "easy" },
  { text: "Az oxigén a levegő legnagyobb összetevője.", answer: false, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "easy" },
  { text: "A gyémánt a Földön előforduló legkeményebb természetes anyag.", answer: true, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "easy" },
  { text: "Az emberi agy 10%-át használja csak.", answer: false, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "easy" },
  { text: "A Nap egy szilárd égitest.", answer: false, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "easy" },
  { text: "A Hold saját fényt bocsát ki.", answer: false, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "easy" },
  { text: "Az emberi testnek 206 csontja van felnőttkorban.", answer: true, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "easy" },
  { text: "A víz kémiai képlete H2O.", answer: true, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "easy" },
  { text: "A Föld a Naprendszer legnagyobb bolygója.", answer: false, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "easy" },
  { text: "Az emberi szívnek négy kamrája van.", answer: true, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "easy" },
  { text: "A gravitáció a Holdon kisebb, mint a Földön.", answer: true, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "easy" },
  { text: "A jég könnyebb a víznél, ezért úszik.", answer: true, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "easy" },
  { text: "Az emberi test legnagyobb szerve a máj.", answer: false, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "easy" },
  { text: "A Föld kering a Nap körül, nem fordítva.", answer: true, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "easy" },
  { text: "A levegő nitrogénből és oxigénből áll főként.", answer: true, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "easy" },
  { text: "Az emberi test vérének nagy részét a fehérvérsejtek adják.", answer: false, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "easy" },
  { text: "A Naprendszerben 8 bolygó van.", answer: true, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "easy" },
  { text: "A hangsebességnél gyorsabb repülőgépet szuperszonikusnak nevezzük.", answer: true, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "easy" },
  { text: "Az emberi tüdő bal és jobb oldalon egyforma méretű.", answer: false, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "easy" },
  { text: "A Föld forgástengelye merőleges a Nap körüli pályájára.", answer: false, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "easy" },
  { text: "Az elektromosság és a mágnesesség összefügg egymással.", answer: true, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "easy" },
  { text: "A Nap a Tejút galaxis közepén helyezkedik el.", answer: false, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "easy" },
  { text: "Az emberi szem a vörös, zöld és kék színre érzékeny.", answer: true, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "easy" },
  { text: "A hőmérséklet Kelvin-skálán nem lehet negatív.", answer: true, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "easy" },
  { text: "A Föld egyetlen természetes holdja van.", answer: true, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "easy" },

  // ╔══════════════════════════════════════════════════════╗
  // ║              TUDOMÁNY – KÖZEPES (25)                 ║
  // ╚══════════════════════════════════════════════════════╝
  { text: "Az emberi testben több baktérium van, mint emberi sejt.", answer: true, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "medium" },
  { text: "A hang gyorsabban terjed vízben, mint levegőben.", answer: true, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "medium" },
  { text: "A víz mindig 100°C-on forr, függetlenül a magasságtól.", answer: false, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "medium" },
  { text: "A Föld forgása lassul az idő múlásával.", answer: true, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "medium" },
  { text: "Az emberi DNS 99%-ban megegyezik a csimpánzéval.", answer: true, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "medium" },
  { text: "A villám soha nem csap kétszer ugyanoda.", answer: false, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "medium" },
  { text: "A vér kék, amíg az erekben van, és csak a levegőn válik pirossá.", answer: false, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "medium" },
  { text: "A Hold gravitációja okozza a Földön az árapályt.", answer: true, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "medium" },
  { text: "Az emberi test több vizet tartalmaz, mint bármilyen más anyagot.", answer: true, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "medium" },
  { text: "A fény lassabb üvegben, mint vákuumban.", answer: true, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "medium" },
  { text: "Az emberi agy kb. 20%-át fogyasztja a test teljes energiájának.", answer: true, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "medium" },
  { text: "A Marson van a Naprendszer legnagyobb vulkánja.", answer: true, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "medium" },
  { text: "Az emberi csontok keményebbek az acélnál.", answer: false, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "medium" },
  { text: "A szén-dioxid nehezebb a levegőnél.", answer: true, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "medium" },
  { text: "Az emberi test minden sejtje pontosan ugyanolyan DNS-t tartalmaz.", answer: true, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "medium" },
  { text: "A Szaturnusznak több holdja van, mint a Jupiternek.", answer: true, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "medium" },
  { text: "A radioaktív bomlás során az atom magja változik meg.", answer: true, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "medium" },
  { text: "Az emberi szem képes infravörös fényt érzékelni.", answer: false, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "medium" },
  { text: "A Föld mágneses északi pólusa nem egyezik meg a földrajzi északi pólussal.", answer: true, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "medium" },
  { text: "A fény egy év alatt kb. 9,5 billió kilométert tesz meg.", answer: true, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "medium" },
  { text: "Az emberi ujjak bőrének ráncai vízben azért keletkeznek, hogy jobb legyen a fogás.", answer: true, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "medium" },
  { text: "A Neptunusz a Naprendszer leghidegebb bolygója.", answer: false, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "medium" },
  { text: "Az emberi test kb. 37 Celsius fokon működik optimálisan.", answer: true, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "medium" },
  { text: "A Föld belseje részben folyékony.", answer: true, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "medium" },
  { text: "A szivárványban mindig pontosan 7 szín látható.", answer: false, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "medium" },

  // ╔══════════════════════════════════════════════════════╗
  // ║              TUDOMÁNY – NEHÉZ (25)                   ║
  // ╚══════════════════════════════════════════════════════╝
  { text: "Az elektron tömege nagyobb, mint a proton tömege.", answer: false, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "hard" },
  { text: "A DNS kettős spirál szerkezetét Watson és Crick írta le 1953-ban.", answer: true, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "hard" },
  { text: "A fény részecskéként és hullámként is viselkedhet egyszerre.", answer: true, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "hard" },
  { text: "A Schrödinger-egyenlet a kvantummechanika alapegyenlete.", answer: true, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "hard" },
  { text: "A fekete lyukakból semmi sem tud kiszabadulni, még a gravitáció sem.", answer: false, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "hard" },
  { text: "Az emberi agy kb. 86 milliárd neuront tartalmaz.", answer: true, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "hard" },
  { text: "A Heisenberg-féle határozatlansági elv szerint nem lehet egyszerre pontosan mérni egy részecske helyzetét és impulzusát.", answer: true, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "hard" },
  { text: "A CRISPR-Cas9 egy fehérjeszintézist segítő enzim.", answer: false, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "hard" },
  { text: "A neutrínók töltés nélküli részecskék, amelyek szinte mindenen áthaladnak.", answer: true, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "hard" },
  { text: "Az abszolút nulla fok -273,15 °C.", answer: true, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "hard" },
  { text: "A Higgs-bozon felfedezéséért 2013-ban Nobel-díjat adtak.", answer: true, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "hard" },
  { text: "A kvantum-összefonódás során az információ a fénysebességnél gyorsabban terjed.", answer: false, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "hard" },
  { text: "Az emberi genom kb. 3 milliárd bázispárból áll.", answer: true, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "hard" },
  { text: "A szupravezető anyagok szobahőmérsékleten is ellenállás nélkül vezetik az áramot.", answer: false, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "hard" },
  { text: "A Chandrasekhar-határ a fehér törpecsillagok maximális tömegét jelöli.", answer: true, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "hard" },
  { text: "A mitokondrium saját DNS-sel rendelkezik.", answer: true, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "hard" },
  { text: "Az általános relativitáselmélet szerint a gravitáció az idő-tér görbülete.", answer: true, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "hard" },
  { text: "A Pauli-féle kizárási elv szerint két fermion nem lehet azonos kvantumállapotban.", answer: true, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "hard" },
  { text: "A prionok nukleinsavat tartalmazó fertőző ágensek.", answer: false, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "hard" },
  { text: "A Doppler-effektus a hang és a fény esetén egyaránt megfigyelhető.", answer: true, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "hard" },
  { text: "Az emberi test sejtjeinek kb. 90%-a vörösvérsejt.", answer: true, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "hard" },
  { text: "A gravitációs hullámokat először 2015-ben észlelték közvetlenül.", answer: true, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "hard" },
  { text: "A telomér rövidülése összefügg az öregedési folyamattal.", answer: true, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "hard" },
  { text: "A Bose-Einstein-kondenzátum a negyedik halmazállapot.", answer: false, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "hard" },
  { text: "Az epigenetika az örökítőanyag szekvenciájának megváltozásával foglalkozik.", answer: false, category: "science", categoryLabel: "🔬 Tudomány", difficulty: "hard" },

  // ╔══════════════════════════════════════════════════════╗
  // ║             TÖRTÉNELEM – KÖNNYŰ (25)                 ║
  // ╚══════════════════════════════════════════════════════╝
  { text: "Az első olimpiai játékokat az ókori Görögországban tartották Kr.e. 776-ban.", answer: true, category: "history", categoryLabel: "📜 Történelem", difficulty: "easy" },
  { text: "A berlini fal 1991-ben omlott le.", answer: false, category: "history", categoryLabel: "📜 Történelem", difficulty: "easy" },
  { text: "A Titanic 1912-ben süllyedt el.", answer: true, category: "history", categoryLabel: "📜 Történelem", difficulty: "easy" },
  { text: "Kolumbusz Kristóf 1492-ben érte el Amerikát.", answer: true, category: "history", categoryLabel: "📜 Történelem", difficulty: "easy" },
  { text: "A második világháború 1945-ben ért véget.", answer: true, category: "history", categoryLabel: "📜 Történelem", difficulty: "easy" },
  { text: "Az első ember a Holdon Neil Armstrong volt.", answer: true, category: "history", categoryLabel: "📜 Történelem", difficulty: "easy" },
  { text: "A francia forradalom a 18. században zajlott.", answer: true, category: "history", categoryLabel: "📜 Történelem", difficulty: "easy" },
  { text: "A Nagy Fal az egyetlen ember alkotta építmény, ami az űrből látható szabad szemmel.", answer: false, category: "history", categoryLabel: "📜 Történelem", difficulty: "easy" },
  { text: "Az egyiptomi piramisokat rabszolgák építették, akiket nem fizettek.", answer: false, category: "history", categoryLabel: "📜 Történelem", difficulty: "easy" },
  { text: "A Római Birodalom fővárosa mindig Róma volt.", answer: false, category: "history", categoryLabel: "📜 Történelem", difficulty: "easy" },
  { text: "Az első világháború 1914-ben kezdődött.", answer: true, category: "history", categoryLabel: "📜 Történelem", difficulty: "easy" },
  { text: "Napóleon Bonaparte francia császár volt.", answer: true, category: "history", categoryLabel: "📜 Történelem", difficulty: "easy" },
  { text: "A hidegháború az USA és a Szovjetunió között zajlott.", answer: true, category: "history", categoryLabel: "📜 Történelem", difficulty: "easy" },
  { text: "Az ókori Rómában a gladiátorok arénában harcoltak.", answer: true, category: "history", categoryLabel: "📜 Történelem", difficulty: "easy" },
  { text: "A Hold-landingre 1969-ben került sor.", answer: true, category: "history", categoryLabel: "📜 Történelem", difficulty: "easy" },
  { text: "A Szovjetunió 1991-ben szűnt meg.", answer: true, category: "history", categoryLabel: "📜 Történelem", difficulty: "easy" },
  { text: "Az ókori görögök feltalálták a demokráciát.", answer: true, category: "history", categoryLabel: "📜 Történelem", difficulty: "easy" },
  { text: "A Magna Carta egy brit törvénydokumentum.", answer: true, category: "history", categoryLabel: "📜 Történelem", difficulty: "easy" },
  { text: "A vikingek soha nem jutottak el Észak-Amerikába.", answer: false, category: "history", categoryLabel: "📜 Történelem", difficulty: "easy" },
  { text: "Az első atombombát Japánban, Tokióra dobták le.", answer: false, category: "history", categoryLabel: "📜 Történelem", difficulty: "easy" },
  { text: "A Szuezi-csatorna Afrikát és Ázsiát köti össze.", answer: false, category: "history", categoryLabel: "📜 Történelem", difficulty: "easy" },
  { text: "Julius Caesar római diktátor volt.", answer: true, category: "history", categoryLabel: "📜 Történelem", difficulty: "easy" },
  { text: "A reneszánsz Itáliából indult el.", answer: true, category: "history", categoryLabel: "📜 Történelem", difficulty: "easy" },
  { text: "Az ókori Egyiptomban a fáraók kizárólag férfiak voltak.", answer: false, category: "history", categoryLabel: "📜 Történelem", difficulty: "easy" },
  { text: "A Szahara sivatag Afrikában található.", answer: true, category: "history", categoryLabel: "📜 Történelem", difficulty: "easy" },

  // ╔══════════════════════════════════════════════════════╗
  // ║             TÖRTÉNELEM – KÖZEPES (25)                ║
  // ╚══════════════════════════════════════════════════════╝
  { text: "Napóleon Bonaparte alacsony termetű volt – alig 157 cm.", answer: false, category: "history", categoryLabel: "📜 Történelem", difficulty: "medium" },
  { text: "Az első világháború előtt Magyarország és Ausztria egy közös állam volt.", answer: true, category: "history", categoryLabel: "📜 Történelem", difficulty: "medium" },
  { text: "A Titanic első útján soha nem volt elég mentőcsónak minden utasnak.", answer: true, category: "history", categoryLabel: "📜 Történelem", difficulty: "medium" },
  { text: "A hidegháború során az USA és a Szovjetunió közvetlen katonai konfliktusba keveredett.", answer: false, category: "history", categoryLabel: "📜 Történelem", difficulty: "medium" },
  { text: "Az ókori Rómában a gladiátorok többsége önként vállalta a harcot.", answer: true, category: "history", categoryLabel: "📜 Történelem", difficulty: "medium" },
  { text: "A Magna Carta 1215-ben született Angliában.", answer: true, category: "history", categoryLabel: "📜 Történelem", difficulty: "medium" },
  { text: "A Szuezi-csatornát 1869-ben nyitották meg.", answer: true, category: "history", categoryLabel: "📜 Történelem", difficulty: "medium" },
  { text: "Az Oszmán Birodalom az első világháborúban a szövetségesek oldalán harcolt.", answer: false, category: "history", categoryLabel: "📜 Történelem", difficulty: "medium" },
  { text: "A Fekete Halál a 14. században Európa népességének kb. egyharmadát ölte meg.", answer: true, category: "history", categoryLabel: "📜 Történelem", difficulty: "medium" },
  { text: "Az első nyomtatott Biblia Gutenberg nevéhez fűződik, és a 15. században készült.", answer: true, category: "history", categoryLabel: "📜 Történelem", difficulty: "medium" },
  { text: "A Versailles-i béke 1919-ben írta elő Németország háborús felelősségét.", answer: true, category: "history", categoryLabel: "📜 Történelem", difficulty: "medium" },
  { text: "A Mongol Birodalom volt valaha a világ legnagyobb összefüggő szárazföldi birodalma.", answer: true, category: "history", categoryLabel: "📜 Történelem", difficulty: "medium" },
  { text: "Az ókori Karthágó mai Tunézia területén feküdt.", answer: true, category: "history", categoryLabel: "📜 Történelem", difficulty: "medium" },
  { text: "A Konstantinápoly elfoglalása 1453-ban az újkor kezdetét jelzi.", answer: true, category: "history", categoryLabel: "📜 Történelem", difficulty: "medium" },
  { text: "A Párizsi Kommün 1871-ben zajlott.", answer: true, category: "history", categoryLabel: "📜 Történelem", difficulty: "medium" },
  { text: "Az USA 1776-ban nyilvánította ki függetlenségét.", answer: true, category: "history", categoryLabel: "📜 Történelem", difficulty: "medium" },
  { text: "A Napóleon elleni orosz hadjárat 1812-ben zajlott.", answer: true, category: "history", categoryLabel: "📜 Történelem", difficulty: "medium" },
  { text: "A Spanyol Armada az angolok ellen indult 1588-ban.", answer: true, category: "history", categoryLabel: "📜 Történelem", difficulty: "medium" },
  { text: "Az ókori Görögországban Spárta és Athén mindig szövetségesek voltak.", answer: false, category: "history", categoryLabel: "📜 Történelem", difficulty: "medium" },
  { text: "A Trianoni béke 1920-ban Magyarország területének kétharmadát elvette.", answer: true, category: "history", categoryLabel: "📜 Történelem", difficulty: "medium" },
  { text: "A Keresztes hadjáratok célja Jeruzsálem visszafoglalása volt.", answer: true, category: "history", categoryLabel: "📜 Történelem", difficulty: "medium" },
  { text: "Az ókori Rómában a szenátus tagjai örökletes nemesek voltak.", answer: false, category: "history", categoryLabel: "📜 Történelem", difficulty: "medium" },
  { text: "A Brit Birodalom volt valaha a világ legnagyobb birodalma területileg.", answer: true, category: "history", categoryLabel: "📜 Történelem", difficulty: "medium" },
  { text: "A Bastille ostroma 1789. július 14-én volt.", answer: true, category: "history", categoryLabel: "📜 Történelem", difficulty: "medium" },
  { text: "Az ókori Egyiptomban a múmiákat kizárólag fáraókból készítették.", answer: false, category: "history", categoryLabel: "📜 Történelem", difficulty: "medium" },

  // ╔══════════════════════════════════════════════════════╗
  // ║             TÖRTÉNELEM – NEHÉZ (25)                  ║
  // ╚══════════════════════════════════════════════════════╝
  { text: "Kleopátra közelebb élt időben a Hold-landinghez, mint az egyiptomi piramisok építéséhez.", answer: true, category: "history", categoryLabel: "📜 Történelem", difficulty: "hard" },
  { text: "A Mongol Birodalom csúcsán a Föld szárazföldi területének kb. 24%-át uralta.", answer: true, category: "history", categoryLabel: "📜 Történelem", difficulty: "hard" },
  { text: "Az ókori Rómában a Colosseum befogadóképessége kb. 50 000 fő volt.", answer: true, category: "history", categoryLabel: "📜 Történelem", difficulty: "hard" },
  { text: "A Konstantinápoly elfoglalása után az Oszmán Birodalom azonnal feloszlatta a Bizánci Egyházat.", answer: false, category: "history", categoryLabel: "📜 Történelem", difficulty: "hard" },
  { text: "Az ókori Athénban a nők szavazhattak a népgyűlésen.", answer: false, category: "history", categoryLabel: "📜 Történelem", difficulty: "hard" },
  { text: "A Hannibal által vezetett karthágói sereg elefántokkal kelt át az Alpokon.", answer: true, category: "history", categoryLabel: "📜 Történelem", difficulty: "hard" },
  { text: "A Harmincéves háború (1618–1648) kizárólag vallási okokból robbant ki.", answer: false, category: "history", categoryLabel: "📜 Történelem", difficulty: "hard" },
  { text: "Az ókori Egyiptomban a hieroglifákat kizárólag papok használhatták.", answer: false, category: "history", categoryLabel: "📜 Történelem", difficulty: "hard" },
  { text: "A Waterlooi csata 1815-ben zajlott.", answer: true, category: "history", categoryLabel: "📜 Történelem", difficulty: "hard" },
  { text: "Az ókori Rómában a Pax Romana kb. 200 éves békés időszakot jelöl.", answer: true, category: "history", categoryLabel: "📜 Történelem", difficulty: "hard" },
  { text: "A Meiji-restauráció Japán modernizációját indította el a 19. században.", answer: true, category: "history", categoryLabel: "📜 Történelem", difficulty: "hard" },
  { text: "Az ókori Görögországban a Peloponnészoszi háborút Athén nyerte.", answer: false, category: "history", categoryLabel: "📜 Történelem", difficulty: "hard" },
  { text: "A Szuezi-csatorna megnyitása előtt a hajóknak Afrika körül kellett kerülniük.", answer: true, category: "history", categoryLabel: "📜 Történelem", difficulty: "hard" },
  { text: "Az inka birodalom fővárosa Tenochtitlan volt.", answer: false, category: "history", categoryLabel: "📜 Történelem", difficulty: "hard" },
  { text: "A Westfáliai béke (1648) az európai nemzetállamok rendszerének alapját rakta le.", answer: true, category: "history", categoryLabel: "📜 Történelem", difficulty: "hard" },
  { text: "Az ókori Kínában a papír feltalálása a Han-dinasztia idejére tehető.", answer: true, category: "history", categoryLabel: "📜 Történelem", difficulty: "hard" },
  { text: "A Fekete Halál Európába a Selyemúton érkező kereskedők révén terjedt.", answer: true, category: "history", categoryLabel: "📜 Történelem", difficulty: "hard" },
  { text: "Az ókori Rómában a Köztársaság időszaka megelőzte a Királyság időszakát.", answer: false, category: "history", categoryLabel: "📜 Történelem", difficulty: "hard" },
  { text: "A Napóleon-ellenes koalíciók összesen hét alkalommal szálltak szembe Franciaországgal.", answer: true, category: "history", categoryLabel: "📜 Történelem", difficulty: "hard" },
  { text: "Az ókori Egyiptomban az Újbirodalom időszakában épültek a nagy piramisok.", answer: false, category: "history", categoryLabel: "📜 Történelem", difficulty: "hard" },
  { text: "A Szovjetunió az első műholdat, a Szputnyikot 1957-ben bocsátotta fel.", answer: true, category: "history", categoryLabel: "📜 Történelem", difficulty: "hard" },
  { text: "Az ókori Görögországban a Szókratész-per Kr.e. 399-ben zajlott.", answer: true, category: "history", categoryLabel: "📜 Történelem", difficulty: "hard" },
  { text: "A Trianoni béke aláírásának helyszíne a versailles-i kastély volt.", answer: false, category: "history", categoryLabel: "📜 Történelem", difficulty: "hard" },
  { text: "Az ókori Rómában a Rubicon folyón való átkelés hadüzenetnek számított.", answer: true, category: "history", categoryLabel: "📜 Történelem", difficulty: "hard" },
  { text: "A Bretton Woods-i egyezmény (1944) az aranystandard rendszert vezette be.", answer: false, category: "history", categoryLabel: "📜 Történelem", difficulty: "hard" },

  // ╔══════════════════════════════════════════════════════╗
  // ║              TERMÉSZET – KÖNNYŰ (25)                 ║
  // ╚══════════════════════════════════════════════════════╝
  { text: "A flamingók azért rózsaszínűek, mert a táplálékukban lévő pigmentek festik meg a tollaikat.", answer: true, category: "nature", categoryLabel: "🌿 Természet", difficulty: "easy" },
  { text: "A banán technikailag egy bogyó.", answer: true, category: "nature", categoryLabel: "🌿 Természet", difficulty: "easy" },
  { text: "A teknősök hallás nélkül élnek – nincs hallószervük.", answer: false, category: "nature", categoryLabel: "🌿 Természet", difficulty: "easy" },
  { text: "A delfinek halak.", answer: false, category: "nature", categoryLabel: "🌿 Természet", difficulty: "easy" },
  { text: "A koala ujjlenyomatai szinte megkülönböztethetetlenek az emberétől.", answer: true, category: "nature", categoryLabel: "🌿 Természet", difficulty: "easy" },
  { text: "A pingvinek csak a Déli-sarkon élnek.", answer: false, category: "nature", categoryLabel: "🌿 Természet", difficulty: "easy" },
  { text: "A méhek elpusztulnak, miután megcsípnek valakit.", answer: true, category: "nature", categoryLabel: "🌿 Természet", difficulty: "easy" },
  { text: "A pillangók ízlelőszerve a lábukban van.", answer: true, category: "nature", categoryLabel: "🌿 Természet", difficulty: "easy" },
  { text: "A cápa az egyetlen hal, amely pislogni tud.", answer: false, category: "nature", categoryLabel: "🌿 Természet", difficulty: "easy" },
  { text: "A kenguruk csak Ausztráliában élnek vadon.", answer: false, category: "nature", categoryLabel: "🌿 Természet", difficulty: "easy" },
  { text: "Az elefánt a szárazföld legnagyobb élő állata.", answer: true, category: "nature", categoryLabel: "🌿 Természet", difficulty: "easy" },
  { text: "A kígyóknak nincs fülük.", answer: true, category: "nature", categoryLabel: "🌿 Természet", difficulty: "easy" },
  { text: "A denevérek vakok.", answer: false, category: "nature", categoryLabel: "🌿 Természet", difficulty: "easy" },
  { text: "A gepárd a világ leggyorsabb szárazföldi állata.", answer: true, category: "nature", categoryLabel: "🌿 Természet", difficulty: "easy" },
  { text: "A bálna a világ legnagyobb állata.", answer: true, category: "nature", categoryLabel: "🌿 Természet", difficulty: "easy" },
  { text: "A kacsacsőrű emlős tojást tojik.", answer: true, category: "nature", categoryLabel: "🌿 Természet", difficulty: "easy" },
  { text: "A krokodilok hüllők.", answer: true, category: "nature", categoryLabel: "🌿 Természet", difficulty: "easy" },
  { text: "A bambusz a világ leggyorsabban növő növénye.", answer: true, category: "nature", categoryLabel: "🌿 Természet", difficulty: "easy" },
  { text: "A medvék téli álmuk alatt egyáltalán nem lélegeznek.", answer: false, category: "nature", categoryLabel: "🌿 Természet", difficulty: "easy" },
  { text: "A polipoknak nyolc karjuk van.", answer: true, category: "nature", categoryLabel: "🌿 Természet", difficulty: "easy" },
  { text: "A hangyák képesek a saját testsúlyuknál sokkal nehezebb terhet cipelni.", answer: true, category: "nature", categoryLabel: "🌿 Természet", difficulty: "easy" },
  { text: "A zsiráf a világ legmagasabb állata.", answer: true, category: "nature", categoryLabel: "🌿 Természet", difficulty: "easy" },
  { text: "A teknős a leghosszabb életű gerinces állat.", answer: true, category: "nature", categoryLabel: "🌿 Természet", difficulty: "easy" },
  { text: "A rovaroknak hat lábuk van.", answer: true, category: "nature", categoryLabel: "🌿 Természet", difficulty: "easy" },
  { text: "A pókoknak nyolc lábuk van.", answer: true, category: "nature", categoryLabel: "🌿 Természet", difficulty: "easy" },

  // ╔══════════════════════════════════════════════════════╗
  // ║              TERMÉSZET – KÖZEPES (25)                ║
  // ╚══════════════════════════════════════════════════════╝
  { text: "A polipoknak három szívük van.", answer: true, category: "nature", categoryLabel: "🌿 Természet", difficulty: "medium" },
  { text: "A méhek képesek felismerni az emberi arcokat.", answer: true, category: "nature", categoryLabel: "🌿 Természet", difficulty: "medium" },
  { text: "A hangyák összesített tömege megközelíti az összes ember összesített tömegét.", answer: true, category: "nature", categoryLabel: "🌿 Természet", difficulty: "medium" },
  { text: "A medúzák 95%-a víz.", answer: true, category: "nature", categoryLabel: "🌿 Természet", difficulty: "medium" },
  { text: "A csigák képesek aludni akár 3 évig is.", answer: true, category: "nature", categoryLabel: "🌿 Természet", difficulty: "medium" },
  { text: "A fák kommunikálnak egymással a gyökereiken keresztül.", answer: true, category: "nature", categoryLabel: "🌿 Természet", difficulty: "medium" },
  { text: "A gepárd a világ leggyorsabb állata hosszú távon is.", answer: false, category: "nature", categoryLabel: "🌿 Természet", difficulty: "medium" },
  { text: "A tintahal vére kék színű.", answer: true, category: "nature", categoryLabel: "🌿 Természet", difficulty: "medium" },
  { text: "A harkályok azért nem kapnak fejfájást, mert a koponyájuk speciálisan párnázott.", answer: true, category: "nature", categoryLabel: "🌿 Természet", difficulty: "medium" },
  { text: "A krokodilok nem változtatnak nemet az életük során.", answer: false, category: "nature", categoryLabel: "🌿 Természet", difficulty: "medium" },
  { text: "A méregnyíl-béka mérgét maga termeli, nem a táplálékából veszi fel.", answer: false, category: "nature", categoryLabel: "🌿 Természet", difficulty: "medium" },
  { text: "A növények éjszaka oxigént vesznek fel és szén-dioxidot bocsátanak ki.", answer: true, category: "nature", categoryLabel: "🌿 Természet", difficulty: "medium" },
  { text: "A bálnák a szárazföldről visszatért emlősök leszármazottai.", answer: true, category: "nature", categoryLabel: "🌿 Természet", difficulty: "medium" },
  { text: "A gomba az állatokhoz közelebb áll evolúciósan, mint a növényekhez.", answer: true, category: "nature", categoryLabel: "🌿 Természet", difficulty: "medium" },
  { text: "A tenger mélyén élő halak egy része biolumineszcenciával világít.", answer: true, category: "nature", categoryLabel: "🌿 Természet", difficulty: "medium" },
  { text: "A fák évgyűrűi alapján meg lehet határozni az éghajlat múltbeli változásait.", answer: true, category: "nature", categoryLabel: "🌿 Természet", difficulty: "medium" },
  { text: "A delfinek alvás közben az agyuk felét ébren tartják.", answer: true, category: "nature", categoryLabel: "🌿 Természet", difficulty: "medium" },
  { text: "A méhek táncukkal kommunikálják a táplálékforrás irányát.", answer: true, category: "nature", categoryLabel: "🌿 Természet", difficulty: "medium" },
  { text: "A kenguruk visszafelé is tudnak ugrani.", answer: false, category: "nature", categoryLabel: "🌿 Természet", difficulty: "medium" },
  { text: "A korallok állatok, nem növények.", answer: true, category: "nature", categoryLabel: "🌿 Természet", difficulty: "medium" },
  { text: "A varjak képesek eszközöket használni és készíteni.", answer: true, category: "nature", categoryLabel: "🌿 Természet", difficulty: "medium" },
  { text: "A csimpánzok képesek megtanulni a jelnyelvből több száz jelet.", answer: true, category: "nature", categoryLabel: "🌿 Természet", difficulty: "medium" },
  { text: "A kígyók kizárólag élő zsákmányt esznek.", answer: false, category: "nature", categoryLabel: "🌿 Természet", difficulty: "medium" },
  { text: "A tengeri csikók a hímek hordják ki a fiókákat.", answer: true, category: "nature", categoryLabel: "🌿 Természet", difficulty: "medium" },
  { text: "A hangyák képesek úszni.", answer: true, category: "nature", categoryLabel: "🌿 Természet", difficulty: "medium" },

  // ╔══════════════════════════════════════════════════════╗
  // ║              TERMÉSZET – NEHÉZ (25)                  ║
  // ╚══════════════════════════════════════════════════════╝
  { text: "A tardigrádák (vízmedvék) képesek túlélni az űr vákuumát.", answer: true, category: "nature", categoryLabel: "🌿 Természet", difficulty: "hard" },
  { text: "A hálóscsík-kígyó a világ leghosszabb kígyója.", answer: true, category: "nature", categoryLabel: "🌿 Természet", difficulty: "hard" },
  { text: "A korallzátonyok az óceán felszínének több mint 10%-át borítják.", answer: false, category: "nature", categoryLabel: "🌿 Természet", difficulty: "hard" },
  { text: "A platypus (kacsacsőrű emlős) az egyetlen méregtermelő emlős.", answer: false, category: "nature", categoryLabel: "🌿 Természet", difficulty: "hard" },
  { text: "A mikoriza-hálózat segítségével a fák tápanyagot osztanak meg egymással.", answer: true, category: "nature", categoryLabel: "🌿 Természet", difficulty: "hard" },
  { text: "A Turritopsis dohrnii medúzafaj biológiailag halhatatlan.", answer: true, category: "nature", categoryLabel: "🌿 Természet", difficulty: "hard" },
  { text: "A mantaráják az egyetlen halak, amelyek önmagukat felismerik a tükörben.", answer: true, category: "nature", categoryLabel: "🌿 Természet", difficulty: "hard" },
  { text: "A növények képesek kémiai jeleket kibocsátani, ha rovarok támadják meg őket.", answer: true, category: "nature", categoryLabel: "🌿 Természet", difficulty: "hard" },
  { text: "A Greenland-i jégpáncél teljes olvadása kb. 7 méteres tengerszint-emelkedést okozna.", answer: true, category: "nature", categoryLabel: "🌿 Természet", difficulty: "hard" },
  { text: "A baktériumok képesek géneket átadni egymásnak szaporodás nélkül is.", answer: true, category: "nature", categoryLabel: "🌿 Természet", difficulty: "hard" },
  { text: "A cápa az egyetlen állat, amely soha nem kap rákot.", answer: false, category: "nature", categoryLabel: "🌿 Természet", difficulty: "hard" },
  { text: "A hangyabolyok egyes fajoknál több millió egyedből állhatnak.", answer: true, category: "nature", categoryLabel: "🌿 Természet", difficulty: "hard" },
  { text: "A növények képesek érzékelni a gravitáció irányát.", answer: true, category: "nature", categoryLabel: "🌿 Természet", difficulty: "hard" },
  { text: "A tintahalak képesek álmodni – REM-fázisuk van.", answer: true, category: "nature", categoryLabel: "🌿 Természet", difficulty: "hard" },
  { text: "A Homo sapiens az egyetlen faj, amely képes önmaga halálának tudatára.", answer: false, category: "nature", categoryLabel: "🌿 Természet", difficulty: "hard" },
  { text: "A méhek képesek elvont fogalmakat, például a 'nullát' megérteni.", answer: true, category: "nature", categoryLabel: "🌿 Természet", difficulty: "hard" },
  { text: "A Földön az összes faj kb. 99%-a már kihalt.", answer: true, category: "nature", categoryLabel: "🌿 Természet", difficulty: "hard" },
  { text: "A polipok képesek álmodni, és alvás közben megváltoztatják a bőrük színét.", answer: true, category: "nature", categoryLabel: "🌿 Természet", difficulty: "hard" },
  { text: "A növények képesek hallani – reagálnak a hangrezgésekre.", answer: true, category: "nature", categoryLabel: "🌿 Természet", difficulty: "hard" },
  { text: "A Homo neanderthalensis és a Homo sapiens soha nem élt egyszerre.", answer: false, category: "nature", categoryLabel: "🌿 Természet", difficulty: "hard" },
  { text: "A vírus nem tekinthető élőlénynek a klasszikus biológiai definíció szerint.", answer: true, category: "nature", categoryLabel: "🌿 Természet", difficulty: "hard" },
  { text: "A Yellowstone-i szupervulkán kb. 640 000 évente tör ki.", answer: true, category: "nature", categoryLabel: "🌿 Természet", difficulty: "hard" },
  { text: "A Föld óceánjai összesen kb. 97%-át teszik ki a Föld összes vizének.", answer: true, category: "nature", categoryLabel: "🌿 Természet", difficulty: "hard" },
  { text: "A csimpánzok és az emberek közös ősétől való elválás kb. 6 millió évvel ezelőtt történt.", answer: true, category: "nature", categoryLabel: "🌿 Természet", difficulty: "hard" },
  { text: "A Föld összes erdőjének több mint fele a trópusokon található.", answer: true, category: "nature", categoryLabel: "🌿 Természet", difficulty: "hard" },

  // ╔══════════════════════════════════════════════════════╗
  // ║            ÉRDEKESSÉGEK – KÖNNYŰ (25)                ║
  // ╚══════════════════════════════════════════════════════╝
  { text: "A méz soha nem romlik meg – évezredes méz is fogyasztható.", answer: true, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "easy" },
  { text: "A Vatikán a világ legkisebb állama.", answer: true, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "easy" },
  { text: "Az emberi ujjlenyomatok egyediek – még az ikreknek is különbözők.", answer: true, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "easy" },
  { text: "A WiFi szó egy rövidítés, a 'Wireless Fidelity' kifejezésből ered.", answer: false, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "easy" },
  { text: "Az emberi szem 10 millió különböző színt képes megkülönböztetni.", answer: true, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "easy" },
  { text: "A Föld tömege minden évben csökken, mert az emberek rakétákat lőnek ki az űrbe.", answer: false, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "easy" },
  { text: "Az emberi test csontjainak több mint fele a kezekben és lábakban található.", answer: true, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "easy" },
  { text: "A Nintendo cég 1889-ben alapult.", answer: true, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "easy" },
  { text: "Az első e-mailt 1971-ben küldték el.", answer: true, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "easy" },
  { text: "A Monopoly játékot eredetileg a kapitalizmus kritikájaként tervezték.", answer: true, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "easy" },
  { text: "Az Eiffel-torony nyáron magasabb, mint télen.", answer: true, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "easy" },
  { text: "A Szahara a világ legnagyobb sivataga.", answer: false, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "easy" },
  { text: "Az emberi köröm gyorsabban nő, mint a lábköröm.", answer: true, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "easy" },
  { text: "A banán radioaktív, mert káliumot tartalmaz.", answer: true, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "easy" },
  { text: "A Lego a világ legnagyobb gumiabroncs-gyártója.", answer: true, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "easy" },
  { text: "Az emberi agy aktívabb alvás közben, mint tévénézés közben.", answer: true, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "easy" },
  { text: "A Rubik-kocka minden állásból legfeljebb 20 lépésben megoldható.", answer: true, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "easy" },
  { text: "Az emberi test minden sejtje tartalmaz DNS-t.", answer: false, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "easy" },
  { text: "A Csendes-óceán nagyobb, mint az összes szárazföld együttvéve.", answer: true, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "easy" },
  { text: "A Plútót 2006-ban sorolták ki a bolygók közül.", answer: true, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "easy" },
  { text: "Az emberi szem felbontása kb. 576 megapixelnek felel meg.", answer: true, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "easy" },
  { text: "A Voyager 1 szonda már elhagyta a Naprendszert.", answer: true, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "easy" },
  { text: "Az emberi test kb. 7 x 10^27 atomból áll.", answer: true, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "easy" },
  { text: "A Szaturnusz sűrűsége kisebb, mint a vízé – elméletileg úszna rajta.", answer: true, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "easy" },
  { text: "Az Oxford Egyetem idősebb, mint az Azték Birodalom.", answer: true, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "easy" },

  // ╔══════════════════════════════════════════════════════╗
  // ║            ÉRDEKESSÉGEK – KÖZEPES (25)               ║
  // ╚══════════════════════════════════════════════════════╝
  { text: "Egy átlagos ember életében kb. 6 évet tölt álmodással.", answer: true, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "medium" },
  { text: "A mammutok még éltek, amikor az egyiptomiak a piramisokat építették.", answer: true, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "medium" },
  { text: "A legtöbb ember naponta kb. 70 000 gondolatot gondol.", answer: true, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "medium" },
  { text: "Az emberi agy kb. 2%-a a testtömegnek, de az energia 20%-át fogyasztja.", answer: true, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "medium" },
  { text: "A Föld mágneses pólusai az elmúlt 780 000 évben nem cseréltek helyet.", answer: false, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "medium" },
  { text: "Az emberi test atomjai kb. 7 évente teljesen kicserélődnek.", answer: false, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "medium" },
  { text: "A Föld forgása miatt a keleti parton lévő tárgyak gyorsabban mozognak, mint a nyugatin.", answer: false, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "medium" },
  { text: "Az emberi szív egy átlagos élet alatt kb. 2,5 milliárdszor ver.", answer: true, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "medium" },
  { text: "A Föld egyenlítőjénél laposabb, mint a pólusoknál.", answer: false, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "medium" },
  { text: "Az emberi agy kb. 25 watt teljesítménnyel működik.", answer: true, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "medium" },
  { text: "A Nap tömege a Naprendszer össztömegének több mint 99%-a.", answer: true, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "medium" },
  { text: "Az emberi test kb. 60 000 km hosszú érrendszerrel rendelkezik.", answer: true, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "medium" },
  { text: "A Föld és a Hold közötti távolság kb. 384 000 km.", answer: true, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "medium" },
  { text: "Az emberi agy kb. 1,4 kg-ot nyom.", answer: true, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "medium" },
  { text: "A Nap fénye kb. 8 perc alatt ér a Földre.", answer: true, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "medium" },
  { text: "Az emberi test kb. 37 billió sejtből áll.", answer: true, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "medium" },
  { text: "A Föld átmérője kb. 12 742 km.", answer: true, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "medium" },
  { text: "Az emberi test kb. 60%-a víz.", answer: true, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "medium" },
  { text: "A Nap kb. 4,6 milliárd éves.", answer: true, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "medium" },
  { text: "Az emberi agy kb. 100 billió szinaptikus kapcsolattal rendelkezik.", answer: true, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "medium" },
  { text: "A Föld kb. 4,5 milliárd éves.", answer: true, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "medium" },
  { text: "Az emberi test kb. 650 izmot tartalmaz.", answer: true, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "medium" },
  { text: "A Nap kb. 1,3 millió Föld méretű gömböt tudna befogadni.", answer: true, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "medium" },
  { text: "Az emberi test kb. 5 liter vért tartalmaz.", answer: true, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "medium" },
  { text: "A Tejút galaxis kb. 100 000 fényév átmérőjű.", answer: true, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "medium" },

  // ╔══════════════════════════════════════════════════════╗
  // ║            ÉRDEKESSÉGEK – NEHÉZ (25)                 ║
  // ╚══════════════════════════════════════════════════════╝
  { text: "A Bretton Woods-i egyezmény (1944) az aranystandard rendszert vezette be.", answer: false, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "hard" },
  { text: "Az emberi agy neuroplaszticitása felnőttkorban is megmarad.", answer: true, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "hard" },
  { text: "A kvantumszámítógépek minden feladatban gyorsabbak a klasszikus számítógépeknél.", answer: false, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "hard" },
  { text: "A Fermat-sejtést Andrew Wiles bizonyította be 1995-ben.", answer: true, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "hard" },
  { text: "A Shannon-entrópia az információelmélet alapfogalma.", answer: true, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "hard" },
  { text: "A Turing-teszt célja annak meghatározása, hogy egy gép képes-e emberi intelligenciát szimulálni.", answer: true, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "hard" },
  { text: "A Nash-egyensúly a játékelméletben azt jelenti, hogy minden játékos a legjobb stratégiát választja a többiek stratégiájától függetlenül.", answer: false, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "hard" },
  { text: "A Gödel-féle nemteljességi tétel szerint minden konzisztens formális rendszerben vannak bizonyíthatatlan állítások.", answer: true, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "hard" },
  { text: "A Moore-törvény szerint a tranzisztorok száma egy chipen kb. 18 havonta megduplázódik.", answer: true, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "hard" },
  { text: "A Bayes-tétel a feltételes valószínűség kiszámítására szolgál.", answer: true, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "hard" },
  { text: "A Dunning-Kruger effektus szerint a kevésbé hozzáértők hajlamosak túlbecsülni saját tudásukat.", answer: true, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "hard" },
  { text: "A Mandelbrot-halmaz egy véges területű, de végtelen kerületű fraktál.", answer: true, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "hard" },
  { text: "A Fibonacci-sorozatban minden szám az előző kettő szorzata.", answer: false, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "hard" },
  { text: "A P vs NP probléma az egyik megoldatlan matematikai kérdés.", answer: true, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "hard" },
  { text: "A Riemann-sejtés a prímszámok eloszlásával kapcsolatos.", answer: true, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "hard" },
  { text: "Az Occam borotvája elve szerint a legegyszerűbb magyarázat mindig a helyes.", answer: false, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "hard" },
  { text: "A Pareto-elv szerint az eredmények 80%-a az okok 20%-ából ered.", answer: true, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "hard" },
  { text: "A Hawking-sugárzás elmélete szerint a fekete lyukak lassan elpárolognak.", answer: true, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "hard" },
  { text: "A Kolmogorov-komplexitás egy szöveg legrövidebb leírásának hosszát méri.", answer: true, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "hard" },
  { text: "A Navier-Stokes egyenletek a folyadékok mozgását írják le.", answer: true, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "hard" },
  { text: "A Monty Hall-probléma megoldása szerint érdemes ajtót váltani.", answer: true, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "hard" },
  { text: "A Zipf-törvény szerint a szavak gyakorisága fordítottan arányos a rangsorukkal.", answer: true, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "hard" },
  { text: "A Benford-törvény szerint a természetes adatokban az 1-es szám vezető számjegyként ritkábban fordul elő.", answer: false, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "hard" },
  { text: "A Szimpszon-paradoxon szerint egy trend megfordulhat, ha az adatokat csoportokra bontják.", answer: true, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "hard" },
  { text: "A Fermi-becslés módszere szerint pontos adatok nélkül is lehet nagyságrendi becslést adni.", answer: true, category: "fun", categoryLabel: "😄 Érdekességek", difficulty: "hard" },

];
